#!/usr/bin/env ruby

puts "Welcome to the tic tac toe game"
puts "Are you ready to play the game ? Y/N"

user_response = gets.chomp()

if user_response.upcase == "Y"
    # Play the game
    puts "      *       *       "
    puts "      *       *       "
    puts "      *       *       "
    puts "* * * * * * * * * * * "
    puts "      *       *       "
    puts "      *       *       "
    puts "      *       *       "
    puts "* * * * * * * * * * * "
    puts "      *       *       "
    puts "      *       *       "
    puts "      *       *       "
elsif user_response.upcase == "N"
    # Close the game
end
